document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <title>Document</title>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <!-- main  -->");
document.writeln("    <div class=\'container\'>");
document.writeln("        <!-- 菜单 -->");
document.writeln("        <div class=\'row title\'>");
document.writeln("            <h1 id=\'caidan\'>菜单</h1>");
document.writeln("        </div>");
document.writeln("        <!-- goods -->");
document.writeln("        <ul class=\'goods row \'>");
document.writeln("            <li class=\'col-md-3 col-6\'><a href=\'/wxcd-bs/菜/蒜香牛肉粒.html\'><img src=\'/wxcd-bs/images/蒜香牛肉粒.png\' alt=\'\'></a></li>");
document.writeln("            <li class=\'col-md-3 col-6\'><a href=\'/wxcd-bs/菜/干煎柠檬鸡.HTML\'><img src=\'/wxcd-bs/images/干煎柠檬鸡.png' alt=\'\'></a></li>");
document.writeln("            <li class=\'col-md-3 col-6\'><a href=\'/wxcd-bs/菜/肉沫土豆泥拌饭.HTML\'><img src=\'/wxcd-bs/images/肉沫土豆泥拌饭.png' alt=\'\'></a></li>");
document.writeln("            <li class=\'col-md-3 col-6\'><a href=\'/wxcd-bs/菜/爆浆芝士牛肉饼.HTML\'><img src=\'/wxcd-bs/images/爆浆芝士牛肉饼.png' alt=\'\'></a></li>");
document.writeln("        </ul>");
document.writeln("        <!-- 甜品 -->");
document.writeln("        <div class=\'row title\'>");
document.writeln("            <h1 id=\'tianpin\'>甜品</h1>");
document.writeln("        </div>");
document.writeln("        <!-- goods -->");
document.writeln("        <ul class=\'goods row\'>");
document.writeln("            <li class=\'col-md-3 col-6\'><a href=\'/wxcd-bs/甜品/巧克力慕斯.html\'><img src=\'/wxcd-bs/images/巧克力慕斯.png' alt=\'\'></a></li>");
document.writeln("            <li class=\'col-md-3 col-6\'><a href=\'/wxcd-bs/甜品/提拉米苏.html\'><img src=\'/wxcd-bs/images/提拉米苏.jpg' alt=\'\'></a></li>");
document.writeln("            <li class=\'col-md-3 col-6\'><a href=\'#\'><img src=\'/wxcd-bs/images/巧克力慕斯.png' alt=\'\'></a></li>");
document.writeln("            <li class=\'col-md-3 col-6\'><a href=\'#\'><img src=\'/wxcd-bs/images/巧克力慕斯.png' alt=\'\'></a></li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("</body>");
document.writeln("</html>");
