document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <title>Document</title>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("    <div class=\'nav\'>");
document.writeln("        <div class=\'home\'>");
document.writeln("            <a href=\'/wxcd-bs/index.html\'>首页</a>");
document.writeln("        </div>");
document.writeln("        <div class=\'nav-right\'>");
document.writeln("            <a href=\'#tianpin\'>甜品</a>");
document.writeln("        </div>");
document.writeln("        <div class=\'nav-right\'>");
document.writeln("            <a href=\'#caidan\'>菜单</a>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</body>");
document.writeln("</html>");